name: made_in_flutter_belgium_data
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  path: ^1.8.0
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  lints: ^2.0.0
  test: ^1.21.0
  model_generator: 6.2.1

model_generator:
  base_directory: src/model
